[ubuntu]
    apt = [
      "build-essential",
      "python3-pip",
      "python3-venv",
      "python3-full",
      "pipx",
      "nodejs",
      "npm",
      "curl",
      "fd-find",
      "fzf",
      "git",
      "jq",
      "libfuse2",
      "openssh-server",
      "ripgrep",
      "shellcheck",
      "htop",
      "sshpass",
      "tree",
      "xinput",
      "file",
      "zsh",
      "zip",
      "ca-certificates",
    ]
    snap = [
      { instance = "nvim", args = "--classic" },
      { instance = "aws-cli", args = "--channel=v1/stable --classic" },
    ]

[homebrew]
    formulae = [
      "tmux",
      "neovim",
      "jq",
      "llvm",
      "ripgrep",
      "fzf",
      "zsh",
      "python@3.12"
    ]
